openapi: 3.0.3
info:
  title: Tichu backend api
  description: Api for the Tichu backend
  version: 0.0.1

servers:
  - url: /api

paths:
  /players/{player-name}:
    post:
      tags:
        - Players
      summary: Creates a player
      operationId: createPlayer
      parameters:
        - name: player-name
          in: path
          description: The name of the player
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'

  /games:
    post:
      tags:
        - Games
      summary: Creates a new game
      operationId: createGame
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'

components:
  schemas:
    Player:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name

    Game:
      type: object
      properties:
        id:
          type: string
      required:
        - id
