openapi: 3.0.3
info:
  title: Tichu backend api
  description: Api for the Tichu backend
  version: 0.0.1

servers:
  - url: /api

paths:
  /users/{user-name}:
    post:
      tags:
        - Users
      summary: Creates a user
      operationId: createUser
      parameters:
        - name: user-name
          in: path
          description: The name of the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /games:
    get:
      tags:
        - Games
      summary: Get a list of all games
      operationId: getGames
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Games'
    post:
      tags:
        - Games
      summary: Creates a game
      operationId: createGame
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'

  /games/{game-id}:
    post:
      tags:
        - Games
      summary: Joins a game
      operationId: joinGame
      parameters:
        - name: game-id
          in: path
          description: The id of the game
          required: true
          schema:
            type: string
        - name: user-id
          in: query
          description: The id of the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JoinGame'


components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name

    Game:
      type: object
      properties:
        id:
          type: string
      required:
        - id

    Games:
      type: object
      properties:
        games:
          type: array
          items:
            $ref: '#/components/schemas/Game'
      required:
        - games

    JoinGame:
      type: object
      properties:
        gameId:
          type: string
        playerId:
          type: string
        playerSeatId:
          type: string
          enum:
            - FIRST
            - SECOND
            - THIRD
            - FOURTH
      required:
        - gameId
        - playerId
        - playerSeatId
