/**
 * Tichu backend api
 * Api for the Tichu backend
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JoinGame { 
    gameId: string;
    playerId: string;
    playerSeatId: JoinGame.PlayerSeatIdEnum;
}
export namespace JoinGame {
    export type PlayerSeatIdEnum = 'FIRST' | 'SECOND' | 'THIRD' | 'FOURTH';
    export const PlayerSeatIdEnum = {
        First: 'FIRST' as PlayerSeatIdEnum,
        Second: 'SECOND' as PlayerSeatIdEnum,
        Third: 'THIRD' as PlayerSeatIdEnum,
        Fourth: 'FOURTH' as PlayerSeatIdEnum
    };
}


