spring:
  datasource:
    url: jdbc:h2:mem:tichudb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
