/**
 * Tichu backend api
 * Api for the Tichu backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {HttpHeaders} from '@angular/common/http';

import {Observable} from 'rxjs';

import {Game, Games, JoinGame} from '../model/models';


import {Configuration} from '../configuration';


export interface GamesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Creates a game
     *
     */
    createGame(extraHttpRequestParams?: any): Observable<Game>;

    /**
     * Get a list of all games
     *
     */
    getGames(extraHttpRequestParams?: any): Observable<Games>;

    /**
     * Joins a game
     *
     * @param gameId The id of the game
     * @param userId The id of the user
     */
    joinGame(gameId: string, userId: string, extraHttpRequestParams?: any): Observable<JoinGame>;

}
